<?xml version="1.0" encoding="utf-8"?><Database Name="MarketECUADOR" Class="BDMarketECDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=MarketECUADOR;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="MarketECUADORConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CATEGORIA" Member="CATEGORIA">
    <Type Name="CATEGORIA">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Categoria" Member="Categoria1" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="CATEGORIA_PRODUCTO" Member="PRODUCTO" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="PRODUCTO" />
    </Type>
  </Table>
  <Table Name="dbo.TRANSPORTISTA" Member="TRANSPORTISTA">
    <Type Name="TRANSPORTISTA">
      <Column Name="IdTransportista" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CedTransportista" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="TRANSPORTISTA_GUIA" Member="GUIA" ThisKey="IdTransportista" OtherKey="Transportista" Type="GUIA" />
    </Type>
  </Table>
  <Table Name="dbo.GUIA" Member="GUIA">
    <Type Name="GUIA">
      <Column Name="IdGuia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdLocal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaSalida" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Transportista" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="cantidad_Item" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GUIA_GUIA_DETALLE" Member="GUIA_DETALLE" ThisKey="IdGuia" OtherKey="IdGuia" Type="GUIA_DETALLE" />
      <Association Name="TRANSPORTISTA_GUIA" Member="TRANSPORTISTA1" ThisKey="Transportista" OtherKey="IdTransportista" Type="TRANSPORTISTA" IsForeignKey="true" />
      <Association Name="LOCAL_GUIA" Member="LOCAL" ThisKey="IdLocal" OtherKey="IdLocal" Type="LOCAL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GUIA_DETALLE" Member="GUIA_DETALLE">
    <Type Name="GUIA_DETALLE">
      <Column Name="IdGuia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="GUIA_GUIA_DETALLE" Member="GUIA" ThisKey="IdGuia" OtherKey="IdGuia" Type="GUIA" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="PRODUCTO_GUIA_DETALLE" Member="PRODUCTO" ThisKey="IdProducto" OtherKey="IdProducto" Type="PRODUCTO" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOCAL" Member="LOCAL">
    <Type Name="LOCAL">
      <Column Name="IdLocal" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="LOCAL_GUIA" Member="GUIA" ThisKey="IdLocal" OtherKey="IdLocal" Type="GUIA" />
    </Type>
  </Table>
  <Table Name="dbo.ORDEN" Member="ORDEN">
    <Type Name="ORDEN">
      <Column Name="IdOrden" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FechaOrden" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaEntrada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ORDEN_ORDEN_DETALLE" Member="ORDEN_DETALLE" ThisKey="IdOrden" OtherKey="IdOrden" Type="ORDEN_DETALLE" />
    </Type>
  </Table>
  <Table Name="dbo.ORDEN_DETALLE" Member="ORDEN_DETALLE">
    <Type Name="ORDEN_DETALLE">
      <Column Name="IdOrden" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CantidadSolicitada" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRecibida" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="ORDEN_ORDEN_DETALLE" Member="ORDEN" ThisKey="IdOrden" OtherKey="IdOrden" Type="ORDEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="PRODUCTO_ORDEN_DETALLE" Member="PRODUCTO" ThisKey="IdProducto" OtherKey="IdProducto" Type="PRODUCTO" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCTO" Member="PRODUCTO">
    <Type Name="PRODUCTO">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PrecioProveedor" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="StockActual" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="StockMinimo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="PRODUCTO_GUIA_DETALLE" Member="GUIA_DETALLE" ThisKey="IdProducto" OtherKey="IdProducto" Type="GUIA_DETALLE" />
      <Association Name="PRODUCTO_ORDEN_DETALLE" Member="ORDEN_DETALLE" ThisKey="IdProducto" OtherKey="IdProducto" Type="ORDEN_DETALLE" />
      <Association Name="PRODUCTO_PRODUCTO_PROVEEDOR" Member="PRODUCTO_PROVEEDOR" ThisKey="IdProducto" OtherKey="IdProducto" Type="PRODUCTO_PROVEEDOR" />
      <Association Name="CATEGORIA_PRODUCTO" Member="CATEGORIA" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="CATEGORIA" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCTO_PROVEEDOR" Member="PRODUCTO_PROVEEDOR">
    <Type Name="PRODUCTO_PROVEEDOR">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaEntrega" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="PRODUCTO_PRODUCTO_PROVEEDOR" Member="PRODUCTO" ThisKey="IdProducto" OtherKey="IdProducto" Type="PRODUCTO" IsForeignKey="true" />
      <Association Name="PROVEEDOR_PRODUCTO_PROVEEDOR" Member="PROVEEDOR" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="PROVEEDOR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PROVEEDOR" Member="PROVEEDOR">
    <Type Name="PROVEEDOR">
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CedProveedor" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Representante" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="PROVEEDOR_PRODUCTO_PROVEEDOR" Member="PRODUCTO_PROVEEDOR" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="PRODUCTO_PROVEEDOR" />
    </Type>
  </Table>
  <Function Name="dbo.cp_ActualizarCategoria" Method="cp_ActualizarCategoria">
    <Parameter Name="Ide" Parameter="ide" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cat" Parameter="cat" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Descp" Parameter="descp" Type="System.String" DbType="VarChar(40)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.cp_EliminarCategoria" Method="cp_EliminarCategoria">
    <Parameter Name="Ide" Parameter="ide" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.cp_InsertarCategoria" Method="cp_InsertarCategoria">
    <Parameter Name="Cat" Parameter="cat" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Descp" Parameter="descp" Type="System.String" DbType="VarChar(40)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.cp_ListarCategoria_Filtro" Method="cp_ListarCategoria_Filtro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="cp_ListarCategoria_FiltroResult">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>