<?xml version="1.0" encoding="utf-8"?><Database Name="MarketECUADOR" Class="BDMarketDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=MarketECUADOR;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="MarketECUADORConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TRANSPORTISTA" Member="TRANSPORTISTA">
    <Type Name="TRANSPORTISTA">
      <Column Name="IdTransportista" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CedTransportista" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="TRANSPORTISTA_GUIA" Member="GUIA" ThisKey="IdTransportista" OtherKey="Transportista" Type="GUIA" />
    </Type>
  </Table>
  <Table Name="dbo.CATEGORIA" Member="CATEGORIA">
    <Type Name="CATEGORIA">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Categoria" Member="Categoria1" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="CATEGORIA_PRODUCTO" Member="PRODUCTO" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="PRODUCTO" />
    </Type>
  </Table>
  <Table Name="dbo.GUIA" Member="GUIA">
    <Type Name="GUIA">
      <Column Name="IdGuia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdLocal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaSalida" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Transportista" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="cantidad_Item" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GUIA_GUIA_DETALLE" Member="GUIA_DETALLE" ThisKey="IdGuia" OtherKey="IdGuia" Type="GUIA_DETALLE" />
      <Association Name="TRANSPORTISTA_GUIA" Member="TRANSPORTISTA1" ThisKey="Transportista" OtherKey="IdTransportista" Type="TRANSPORTISTA" IsForeignKey="true" />
      <Association Name="LOCAL_GUIA" Member="LOCAL" ThisKey="IdLocal" OtherKey="IdLocal" Type="LOCAL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GUIA_DETALLE" Member="GUIA_DETALLE">
    <Type Name="GUIA_DETALLE">
      <Column Name="IdGuia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="GUIA_GUIA_DETALLE" Member="GUIA" ThisKey="IdGuia" OtherKey="IdGuia" Type="GUIA" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="PRODUCTO_GUIA_DETALLE" Member="PRODUCTO" ThisKey="IdProducto" OtherKey="IdProducto" Type="PRODUCTO" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOCAL" Member="LOCAL">
    <Type Name="LOCAL">
      <Column Name="IdLocal" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="LOCAL_GUIA" Member="GUIA" ThisKey="IdLocal" OtherKey="IdLocal" Type="GUIA" />
    </Type>
  </Table>
  <Table Name="dbo.ORDEN" Member="ORDEN">
    <Type Name="ORDEN">
      <Column Name="IdOrden" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FechaOrden" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaEntrada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ORDEN_ORDEN_DETALLE" Member="ORDEN_DETALLE" ThisKey="IdOrden" OtherKey="IdOrden" Type="ORDEN_DETALLE" />
    </Type>
  </Table>
  <Table Name="dbo.ORDEN_DETALLE" Member="ORDEN_DETALLE">
    <Type Name="ORDEN_DETALLE">
      <Column Name="IdOrden" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CantidadSolicitada" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CantidadRecibida" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="ORDEN_ORDEN_DETALLE" Member="ORDEN" ThisKey="IdOrden" OtherKey="IdOrden" Type="ORDEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="PRODUCTO_ORDEN_DETALLE" Member="PRODUCTO" ThisKey="IdProducto" OtherKey="IdProducto" Type="PRODUCTO" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCTO" Member="PRODUCTO">
    <Type Name="PRODUCTO">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioProveedor" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockActual" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="StockMinimo" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="PRODUCTO_GUIA_DETALLE" Member="GUIA_DETALLE" ThisKey="IdProducto" OtherKey="IdProducto" Type="GUIA_DETALLE" />
      <Association Name="PRODUCTO_ORDEN_DETALLE" Member="ORDEN_DETALLE" ThisKey="IdProducto" OtherKey="IdProducto" Type="ORDEN_DETALLE" />
      <Association Name="PRODUCTO_PRODUCTO_PROVEEDOR" Member="PRODUCTO_PROVEEDOR" ThisKey="IdProducto" OtherKey="IdProducto" Type="PRODUCTO_PROVEEDOR" />
      <Association Name="CATEGORIA_PRODUCTO" Member="CATEGORIA" ThisKey="IdCategoria" OtherKey="IdCategoria" Type="CATEGORIA" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCTO_PROVEEDOR" Member="PRODUCTO_PROVEEDOR">
    <Type Name="PRODUCTO_PROVEEDOR">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaEntrega" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="PRODUCTO_PRODUCTO_PROVEEDOR" Member="PRODUCTO" ThisKey="IdProducto" OtherKey="IdProducto" Type="PRODUCTO" IsForeignKey="true" />
      <Association Name="PROVEEDOR_PRODUCTO_PROVEEDOR" Member="PROVEEDOR" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="PROVEEDOR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PROVEEDOR" Member="PROVEEDOR">
    <Type Name="PROVEEDOR">
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CedProveedor" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Representante" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="PROVEEDOR_PRODUCTO_PROVEEDOR" Member="PRODUCTO_PROVEEDOR" ThisKey="IdProveedor" OtherKey="IdProveedor" Type="PRODUCTO_PROVEEDOR" />
    </Type>
  </Table>
  <Function Name="dbo.SP_ActualizarCategoria" Method="SP_ActualizarCategoria">
    <Parameter Name="Ide" Parameter="ide" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cat" Parameter="cat" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Descp" Parameter="descp" Type="System.String" DbType="VarChar(40)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_VerCategoria" Method="SP_VerCategoria">
    <ElementType Name="SP_VerCategoriaResult">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ActualizarLocal" Method="SP_ActualizarLocal">
    <Parameter Name="idLocal" Type="System.Int32" DbType="Int" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="ciudad" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="fax" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ActualizarProveedor" Method="SP_ActualizarProveedor">
    <Parameter Name="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="cedProveedor" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="representante" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="ciudad" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="fax" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarCategoria" Method="SP_EliminarCategoria">
    <Parameter Name="Ide" Parameter="ide" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarLocal" Method="SP_EliminarLocal">
    <Parameter Name="idLocal" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarProducto" Method="SP_EliminarProducto">
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarProveedor" Method="SP_EliminarProveedor">
    <Parameter Name="idProveedor" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarCategoria" Method="SP_InsertarCategoria">
    <Parameter Name="Cat" Parameter="cat" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Descp" Parameter="descp" Type="System.String" DbType="VarChar(40)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarLocal" Method="SP_InsertarLocal">
    <Parameter Name="idLocal" Type="System.Int32" DbType="Int" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="ciudad" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="fax" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarProveedor" Method="SP_InsertarProveedor">
    <Parameter Name="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="cedProveedor" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="representante" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="ciudad" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="fax" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarCategoria_Filtro" Method="SP_ListarCategoria_Filtro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarCategoria_FiltroResult">
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarLocal_Filtro" Method="SP_ListarLocal_Filtro">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarLocal_FiltroResult">
      <Column Name="IdLocal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarProducto_Filtro" Method="SP_ListarProducto_Filtro">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarProducto_FiltroResult">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioProveedor" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockActual" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="StockMinimo" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarProveedor_Filtro" Method="SP_ListarProveedor_Filtro">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarProveedor_FiltroResult">
      <Column Name="IdProveedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CedProveedor" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Representante" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ActualizarOrden" Method="SP_ActualizarOrden">
    <Parameter Name="IdOrden" Parameter="idOrden" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaOrden" Parameter="fechaOrden" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaEntrada" Parameter="fechaEntrada" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarGuia" Method="SP_EliminarGuia">
    <Parameter Name="IdGuia" Parameter="idGuia" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarOrden" Method="SP_EliminarOrden">
    <Parameter Name="IdOrden" Parameter="idOrden" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarOrden" Method="SP_InsertarOrden">
    <Parameter Name="FechaOrden" Parameter="fechaOrden" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FechaEntrada" Parameter="fechaEntrada" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarOrden_Filtro" Method="SP_ListarOrden_Filtro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarOrden_FiltroResult">
      <Column Name="IdOrden" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaOrden" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaEntrada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarProductoCategoriaFiltro" Method="SP_ListarProductoCategoriaFiltro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarProductoCategoriaFiltroResult">
      <Column Name="Categoria" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Proveedor" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrecioProveedor" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockActual" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="StockMinimo" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_Insertar_RelProveedorProducto" Method="SP_Insertar_RelProveedorProducto">
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_Eliminar_RelProveedorProducto" Method="SP_Eliminar_RelProveedorProducto">
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ActualizarRelProveedorProducto" Method="SP_ActualizarRelProveedorProducto">
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarProducto" Method="SP_InsertarProducto">
    <Parameter Name="idcat" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="unidadMedida" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="precioProveedor" Type="System.Decimal" DbType="Money" />
    <Parameter Name="stockActual" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="stockMinimo" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="precioVenta" Type="System.Decimal" DbType="Money" />
    <ElementType Name="SP_InsertarProductoResult">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GetProducto" Method="SP_GetProducto">
    <Parameter Name="idCat" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_GetProductoResult">
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="UnidadMedida" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioProveedor" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StockActual" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="StockMinimo" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ActualizarProducto" Method="SP_ActualizarProducto">
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="idCategoria" Type="System.Int32" DbType="Int" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="unidadMedida" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="precioProveedor" Type="System.Decimal" DbType="Money" />
    <Parameter Name="stockActual" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="stockMinimo" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="precioVenta" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ActualizarTransportista" Method="SP_ActualizarTransportista">
    <Parameter Name="idTransportista" Type="System.Int32" DbType="Int" />
    <Parameter Name="cedTransportista" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="ciudad" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_EliminarTransportista" Method="SP_EliminarTransportista">
    <Parameter Name="IdTransportista" Parameter="idTransportista" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarTransportista" Method="SP_InsertarTransportista">
    <Parameter Name="IdTransportista" Parameter="idTransportista" Type="System.Int32" DbType="Int" />
    <Parameter Name="CedTransportista" Parameter="cedTransportista" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(60)" />
    <Parameter Name="Ciudad" Parameter="ciudad" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_InsertarGuia" Method="SP_InsertarGuia">
    <Parameter Name="IdLocal" Parameter="idLocal" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaSalida" Parameter="fechaSalida" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Transportista" Parameter="transportista" Type="System.Int32" DbType="Int" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Money" />
    <Parameter Name="cantidad_Item" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ActualizarGuia" Method="SP_ActualizarGuia">
    <Parameter Name="IdGuia" Parameter="idGuia" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdLocal" Parameter="idLocal" Type="System.Int32" DbType="Int" />
    <Parameter Name="FechaSalida" Parameter="fechaSalida" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Transportista" Parameter="transportista" Type="System.Int32" DbType="Int" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Money" />
    <Parameter Name="cantidad_Item" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarTransportista_Filtro" Method="SP_ListarTransportista_Filtro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarTransportista_FiltroResult">
      <Column Name="IdTransportista" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CedTransportista" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarGuia_Filtro" Method="SP_ListarGuia_Filtro">
    <Parameter Name="Valor" Parameter="valor" Type="System.String" DbType="VarChar(40)" />
    <ElementType Name="SP_ListarGuia_FiltroResult">
      <Column Name="IdGuia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdLocal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaSalida" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Transportista" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="cantidad_Item" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GetGuia" Method="SP_GetGuia">
    <Parameter Name="idLocal" Type="System.Int32" DbType="Int" />
    <Parameter Name="idTransportista" Type="System.Int32" DbType="Int" />
    <Parameter Name="total" Type="System.Decimal" DbType="Money" />
    <Parameter Name="cantidad_item" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_GetGuiaResult">
      <Column Name="IdGuia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdLocal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaSalida" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Transportista" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="cantidad_Item" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_InsertarGuiaDetalle" Method="SP_InsertarGuiaDetalle">
    <Parameter Name="idGuia" Type="System.Int32" DbType="Int" />
    <Parameter Name="idProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="subtotal" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarGuiaDetalle" Method="SP_ListarGuiaDetalle">
    <Parameter Name="idGuia" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarGuiaDetalleResult">
      <Column Name="IdGuia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>