#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MarketECUADOR")]
	public partial class BDMarketDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCATEGORIA(CATEGORIA instance);
    partial void UpdateCATEGORIA(CATEGORIA instance);
    partial void DeleteCATEGORIA(CATEGORIA instance);
    partial void InsertGUIA(GUIA instance);
    partial void UpdateGUIA(GUIA instance);
    partial void DeleteGUIA(GUIA instance);
    partial void InsertGUIA_DETALLE(GUIA_DETALLE instance);
    partial void UpdateGUIA_DETALLE(GUIA_DETALLE instance);
    partial void DeleteGUIA_DETALLE(GUIA_DETALLE instance);
    partial void InsertLOCAL(LOCAL instance);
    partial void UpdateLOCAL(LOCAL instance);
    partial void DeleteLOCAL(LOCAL instance);
    partial void InsertORDEN(ORDEN instance);
    partial void UpdateORDEN(ORDEN instance);
    partial void DeleteORDEN(ORDEN instance);
    partial void InsertORDEN_DETALLE(ORDEN_DETALLE instance);
    partial void UpdateORDEN_DETALLE(ORDEN_DETALLE instance);
    partial void DeleteORDEN_DETALLE(ORDEN_DETALLE instance);
    partial void InsertPRODUCTO(PRODUCTO instance);
    partial void UpdatePRODUCTO(PRODUCTO instance);
    partial void DeletePRODUCTO(PRODUCTO instance);
    partial void InsertPROVEEDOR(PROVEEDOR instance);
    partial void UpdatePROVEEDOR(PROVEEDOR instance);
    partial void DeletePROVEEDOR(PROVEEDOR instance);
    partial void InsertTRANSPORTISTA(TRANSPORTISTA instance);
    partial void UpdateTRANSPORTISTA(TRANSPORTISTA instance);
    partial void DeleteTRANSPORTISTA(TRANSPORTISTA instance);
    #endregion
		
		public BDMarketDataContext() : 
				base(global::Datos.Properties.Settings.Default.MarketECUADORConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BDMarketDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDMarketDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDMarketDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDMarketDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CATEGORIA> CATEGORIA
		{
			get
			{
				return this.GetTable<CATEGORIA>();
			}
		}
		
		public System.Data.Linq.Table<GUIA> GUIA
		{
			get
			{
				return this.GetTable<GUIA>();
			}
		}
		
		public System.Data.Linq.Table<GUIA_DETALLE> GUIA_DETALLE
		{
			get
			{
				return this.GetTable<GUIA_DETALLE>();
			}
		}
		
		public System.Data.Linq.Table<LOCAL> LOCAL
		{
			get
			{
				return this.GetTable<LOCAL>();
			}
		}
		
		public System.Data.Linq.Table<ORDEN> ORDEN
		{
			get
			{
				return this.GetTable<ORDEN>();
			}
		}
		
		public System.Data.Linq.Table<ORDEN_DETALLE> ORDEN_DETALLE
		{
			get
			{
				return this.GetTable<ORDEN_DETALLE>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCTO> PRODUCTO
		{
			get
			{
				return this.GetTable<PRODUCTO>();
			}
		}
		
		public System.Data.Linq.Table<PRODUCTO_PROVEEDOR> PRODUCTO_PROVEEDOR
		{
			get
			{
				return this.GetTable<PRODUCTO_PROVEEDOR>();
			}
		}
		
		public System.Data.Linq.Table<PROVEEDOR> PROVEEDOR
		{
			get
			{
				return this.GetTable<PROVEEDOR>();
			}
		}
		
		public System.Data.Linq.Table<TRANSPORTISTA> TRANSPORTISTA
		{
			get
			{
				return this.GetTable<TRANSPORTISTA>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarCategoria")]
		public int SP_ActualizarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ide", DbType="Int")] System.Nullable<int> ide, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cat", DbType="VarChar(30)")] string cat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descp", DbType="VarChar(40)")] string descp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ide, cat, descp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_VerCategoria")]
		public ISingleResult<SP_VerCategoriaResult> SP_VerCategoria()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_VerCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarLocal")]
		public int SP_ActualizarLocal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idLocal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string fax)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idLocal, direccion, ciudad, telefono, fax);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarProveedor")]
		public int SP_ActualizarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cedProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string representante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string fax)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor, cedProveedor, nombre, representante, direccion, ciudad, telefono, fax);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarCategoria")]
		public int SP_EliminarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ide", DbType="Int")] System.Nullable<int> ide)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ide);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarLocal")]
		public int SP_EliminarLocal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idLocal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idLocal);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarProducto")]
		public int SP_EliminarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarProveedor")]
		public int SP_EliminarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProveedor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarCategoria")]
		public int SP_InsertarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cat", DbType="VarChar(30)")] string cat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descp", DbType="VarChar(40)")] string descp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cat, descp);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarLocal")]
		public int SP_InsertarLocal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idLocal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string fax)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idLocal, direccion, ciudad, telefono, fax);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarProveedor")]
		public int SP_InsertarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cedProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string representante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string fax)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor, cedProveedor, nombre, representante, direccion, ciudad, telefono, fax);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarCategoria_Filtro")]
		public ISingleResult<SP_ListarCategoria_FiltroResult> SP_ListarCategoria_Filtro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarCategoria_FiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarLocal_Filtro")]
		public ISingleResult<SP_ListarLocal_FiltroResult> SP_ListarLocal_Filtro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<SP_ListarLocal_FiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarProducto_Filtro")]
		public ISingleResult<SP_ListarProducto_FiltroResult> SP_ListarProducto_Filtro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<SP_ListarProducto_FiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarProveedor_Filtro")]
		public ISingleResult<SP_ListarProveedor_FiltroResult> SP_ListarProveedor_Filtro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre);
			return ((ISingleResult<SP_ListarProveedor_FiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarOrden")]
		public int SP_ActualizarOrden([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdOrden", DbType="Int")] System.Nullable<int> idOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaOrden", DbType="DateTime")] System.Nullable<System.DateTime> fechaOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaEntrada", DbType="DateTime")] System.Nullable<System.DateTime> fechaEntrada)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden, fechaOrden, fechaEntrada);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarGuia")]
		public int SP_EliminarGuia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdGuia", DbType="Int")] System.Nullable<int> idGuia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idGuia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarOrden")]
		public int SP_EliminarOrden([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdOrden", DbType="Int")] System.Nullable<int> idOrden)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idOrden);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarTransportista")]
		public int SP_EliminarTransportista([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTransportista", DbType="VarChar(30)")] string idTransportista)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTransportista);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarGuia")]
		public int SP_InsertarGuia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdLocal", DbType="Int")] System.Nullable<int> idLocal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaSalida", DbType="DateTime")] System.Nullable<System.DateTime> fechaSalida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Transportista", DbType="VarChar(30)")] string transportista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Money")] System.Nullable<decimal> total, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad_Item)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idLocal, fechaSalida, transportista, total, cantidad_Item);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarOrden")]
		public int SP_InsertarOrden([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaOrden", DbType="DateTime")] System.Nullable<System.DateTime> fechaOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaEntrada", DbType="DateTime")] System.Nullable<System.DateTime> fechaEntrada)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fechaOrden, fechaEntrada);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarTransportista")]
		public int SP_InsertarTransportista([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTransportista", DbType="VarChar(30)")] string idTransportista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CedTransportista", DbType="VarChar(10)")] string cedTransportista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(60)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ciudad", DbType="VarChar(15)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(15)")] string telefono)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTransportista, cedTransportista, nombre, direccion, ciudad, telefono);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarGuia_Filtro")]
		public ISingleResult<SP_ListarGuia_FiltroResult> SP_ListarGuia_Filtro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarGuia_FiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarOrden_Filtro")]
		public ISingleResult<SP_ListarOrden_FiltroResult> SP_ListarOrden_Filtro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarOrden_FiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarTransportista_Filtro")]
		public ISingleResult<SP_ListarTransportista_FiltroResult> SP_ListarTransportista_Filtro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarTransportista_FiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarTransportista")]
		public int SP_ActualizarTransportista([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string idTransportista, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string cedTransportista, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string telefono)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTransportista, cedTransportista, nombre, direccion, ciudad, telefono);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarGuia")]
		public int SP_ActualizarGuia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdGuia", DbType="Int")] System.Nullable<int> idGuia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdLocal", DbType="Int")] System.Nullable<int> idLocal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaSalida", DbType="DateTime")] System.Nullable<System.DateTime> fechaSalida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Transportista", DbType="VarChar(30)")] string transportista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Money")] System.Nullable<decimal> total, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad_Item)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idGuia, idLocal, fechaSalida, transportista, total, cantidad_Item);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarProductoCategoriaFiltro")]
		public ISingleResult<SP_ListarProductoCategoriaFiltroResult> SP_ListarProductoCategoriaFiltro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<SP_ListarProductoCategoriaFiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Insertar_RelProveedorProducto")]
		public int SP_Insertar_RelProveedorProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, idProveedor, fecha);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Eliminar_RelProveedorProducto")]
		public int SP_Eliminar_RelProveedorProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarRelProveedorProducto")]
		public int SP_ActualizarRelProveedorProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, idProveedor, fecha);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarProducto")]
		public ISingleResult<SP_InsertarProductoResult> SP_InsertarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idcat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string unidadMedida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> precioProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> stockActual, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> stockMinimo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> precioVenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idcat, nombre, unidadMedida, precioProveedor, stockActual, stockMinimo, precioVenta);
			return ((ISingleResult<SP_InsertarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GetProducto")]
		public ISingleResult<SP_GetProductoResult> SP_GetProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCat, nombre);
			return ((ISingleResult<SP_GetProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarProducto")]
		public int SP_ActualizarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string unidadMedida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> precioProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> stockActual, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> stockMinimo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> precioVenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, idCategoria, nombre, unidadMedida, precioProveedor, stockActual, stockMinimo, precioVenta);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CATEGORIA")]
	public partial class CATEGORIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCategoria;
		
		private string _Categoria1;
		
		private string _Descripcion;
		
		private EntitySet<PRODUCTO> _PRODUCTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCategoriaChanging(int value);
    partial void OnIdCategoriaChanged();
    partial void OnCategoria1Changing(string value);
    partial void OnCategoria1Changed();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public CATEGORIA()
		{
			this._PRODUCTO = new EntitySet<PRODUCTO>(new Action<PRODUCTO>(this.attach_PRODUCTO), new Action<PRODUCTO>(this.detach_PRODUCTO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this.OnIdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IdCategoria = value;
					this.SendPropertyChanged("IdCategoria");
					this.OnIdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Categoria", Storage="_Categoria1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Categoria1
		{
			get
			{
				return this._Categoria1;
			}
			set
			{
				if ((this._Categoria1 != value))
				{
					this.OnCategoria1Changing(value);
					this.SendPropertyChanging();
					this._Categoria1 = value;
					this.SendPropertyChanged("Categoria1");
					this.OnCategoria1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(40)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIA_PRODUCTO", Storage="_PRODUCTO", ThisKey="IdCategoria", OtherKey="IdCategoria")]
		public EntitySet<PRODUCTO> PRODUCTO
		{
			get
			{
				return this._PRODUCTO;
			}
			set
			{
				this._PRODUCTO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIA = this;
		}
		
		private void detach_PRODUCTO(PRODUCTO entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GUIA")]
	public partial class GUIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGuia;
		
		private int _IdLocal;
		
		private System.DateTime _FechaSalida;
		
		private string _Transportista;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<int> _cantidad_Item;
		
		private EntitySet<GUIA_DETALLE> _GUIA_DETALLE;
		
		private EntityRef<LOCAL> _LOCAL;
		
		private EntityRef<TRANSPORTISTA> _TRANSPORTISTA1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGuiaChanging(int value);
    partial void OnIdGuiaChanged();
    partial void OnIdLocalChanging(int value);
    partial void OnIdLocalChanged();
    partial void OnFechaSalidaChanging(System.DateTime value);
    partial void OnFechaSalidaChanged();
    partial void OnTransportistaChanging(string value);
    partial void OnTransportistaChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void Oncantidad_ItemChanging(System.Nullable<int> value);
    partial void Oncantidad_ItemChanged();
    #endregion
		
		public GUIA()
		{
			this._GUIA_DETALLE = new EntitySet<GUIA_DETALLE>(new Action<GUIA_DETALLE>(this.attach_GUIA_DETALLE), new Action<GUIA_DETALLE>(this.detach_GUIA_DETALLE));
			this._LOCAL = default(EntityRef<LOCAL>);
			this._TRANSPORTISTA1 = default(EntityRef<TRANSPORTISTA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGuia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdGuia
		{
			get
			{
				return this._IdGuia;
			}
			set
			{
				if ((this._IdGuia != value))
				{
					this.OnIdGuiaChanging(value);
					this.SendPropertyChanging();
					this._IdGuia = value;
					this.SendPropertyChanged("IdGuia");
					this.OnIdGuiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLocal", DbType="Int NOT NULL")]
		public int IdLocal
		{
			get
			{
				return this._IdLocal;
			}
			set
			{
				if ((this._IdLocal != value))
				{
					if (this._LOCAL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdLocalChanging(value);
					this.SendPropertyChanging();
					this._IdLocal = value;
					this.SendPropertyChanged("IdLocal");
					this.OnIdLocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSalida", DbType="DateTime NOT NULL")]
		public System.DateTime FechaSalida
		{
			get
			{
				return this._FechaSalida;
			}
			set
			{
				if ((this._FechaSalida != value))
				{
					this.OnFechaSalidaChanging(value);
					this.SendPropertyChanging();
					this._FechaSalida = value;
					this.SendPropertyChanged("FechaSalida");
					this.OnFechaSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transportista", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Transportista
		{
			get
			{
				return this._Transportista;
			}
			set
			{
				if ((this._Transportista != value))
				{
					if (this._TRANSPORTISTA1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTransportistaChanging(value);
					this.SendPropertyChanging();
					this._Transportista = value;
					this.SendPropertyChanged("Transportista");
					this.OnTransportistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_Item", DbType="Int")]
		public System.Nullable<int> cantidad_Item
		{
			get
			{
				return this._cantidad_Item;
			}
			set
			{
				if ((this._cantidad_Item != value))
				{
					this.Oncantidad_ItemChanging(value);
					this.SendPropertyChanging();
					this._cantidad_Item = value;
					this.SendPropertyChanged("cantidad_Item");
					this.Oncantidad_ItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GUIA_GUIA_DETALLE", Storage="_GUIA_DETALLE", ThisKey="IdGuia", OtherKey="IdGuia")]
		public EntitySet<GUIA_DETALLE> GUIA_DETALLE
		{
			get
			{
				return this._GUIA_DETALLE;
			}
			set
			{
				this._GUIA_DETALLE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOCAL_GUIA", Storage="_LOCAL", ThisKey="IdLocal", OtherKey="IdLocal", IsForeignKey=true)]
		public LOCAL LOCAL
		{
			get
			{
				return this._LOCAL.Entity;
			}
			set
			{
				LOCAL previousValue = this._LOCAL.Entity;
				if (((previousValue != value) 
							|| (this._LOCAL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOCAL.Entity = null;
						previousValue.GUIA.Remove(this);
					}
					this._LOCAL.Entity = value;
					if ((value != null))
					{
						value.GUIA.Add(this);
						this._IdLocal = value.IdLocal;
					}
					else
					{
						this._IdLocal = default(int);
					}
					this.SendPropertyChanged("LOCAL");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANSPORTISTA_GUIA", Storage="_TRANSPORTISTA1", ThisKey="Transportista", OtherKey="IdTransportista", IsForeignKey=true)]
		public TRANSPORTISTA TRANSPORTISTA1
		{
			get
			{
				return this._TRANSPORTISTA1.Entity;
			}
			set
			{
				TRANSPORTISTA previousValue = this._TRANSPORTISTA1.Entity;
				if (((previousValue != value) 
							|| (this._TRANSPORTISTA1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRANSPORTISTA1.Entity = null;
						previousValue.GUIA.Remove(this);
					}
					this._TRANSPORTISTA1.Entity = value;
					if ((value != null))
					{
						value.GUIA.Add(this);
						this._Transportista = value.IdTransportista;
					}
					else
					{
						this._Transportista = default(string);
					}
					this.SendPropertyChanged("TRANSPORTISTA1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GUIA_DETALLE(GUIA_DETALLE entity)
		{
			this.SendPropertyChanging();
			entity.GUIA = this;
		}
		
		private void detach_GUIA_DETALLE(GUIA_DETALLE entity)
		{
			this.SendPropertyChanging();
			entity.GUIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GUIA_DETALLE")]
	public partial class GUIA_DETALLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdGuia;
		
		private int _IdProducto;
		
		private short _Cantidad;
		
		private System.Nullable<decimal> _Subtotal;
		
		private EntityRef<GUIA> _GUIA;
		
		private EntityRef<PRODUCTO> _PRODUCTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdGuiaChanging(int value);
    partial void OnIdGuiaChanged();
    partial void OnIdProductoChanging(int value);
    partial void OnIdProductoChanged();
    partial void OnCantidadChanging(short value);
    partial void OnCantidadChanged();
    partial void OnSubtotalChanging(System.Nullable<decimal> value);
    partial void OnSubtotalChanged();
    #endregion
		
		public GUIA_DETALLE()
		{
			this._GUIA = default(EntityRef<GUIA>);
			this._PRODUCTO = default(EntityRef<PRODUCTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGuia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdGuia
		{
			get
			{
				return this._IdGuia;
			}
			set
			{
				if ((this._IdGuia != value))
				{
					if (this._GUIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdGuiaChanging(value);
					this.SendPropertyChanging();
					this._IdGuia = value;
					this.SendPropertyChanged("IdGuia");
					this.OnIdGuiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					if (this._PRODUCTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProductoChanging(value);
					this.SendPropertyChanging();
					this._IdProducto = value;
					this.SendPropertyChanged("IdProducto");
					this.OnIdProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="SmallInt NOT NULL")]
		public short Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Money")]
		public System.Nullable<decimal> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this.OnSubtotalChanging(value);
					this.SendPropertyChanging();
					this._Subtotal = value;
					this.SendPropertyChanged("Subtotal");
					this.OnSubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GUIA_GUIA_DETALLE", Storage="_GUIA", ThisKey="IdGuia", OtherKey="IdGuia", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public GUIA GUIA
		{
			get
			{
				return this._GUIA.Entity;
			}
			set
			{
				GUIA previousValue = this._GUIA.Entity;
				if (((previousValue != value) 
							|| (this._GUIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GUIA.Entity = null;
						previousValue.GUIA_DETALLE.Remove(this);
					}
					this._GUIA.Entity = value;
					if ((value != null))
					{
						value.GUIA_DETALLE.Add(this);
						this._IdGuia = value.IdGuia;
					}
					else
					{
						this._IdGuia = default(int);
					}
					this.SendPropertyChanged("GUIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_GUIA_DETALLE", Storage="_PRODUCTO", ThisKey="IdProducto", OtherKey="IdProducto", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public PRODUCTO PRODUCTO
		{
			get
			{
				return this._PRODUCTO.Entity;
			}
			set
			{
				PRODUCTO previousValue = this._PRODUCTO.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCTO.Entity = null;
						previousValue.GUIA_DETALLE.Remove(this);
					}
					this._PRODUCTO.Entity = value;
					if ((value != null))
					{
						value.GUIA_DETALLE.Add(this);
						this._IdProducto = value.IdProducto;
					}
					else
					{
						this._IdProducto = default(int);
					}
					this.SendPropertyChanged("PRODUCTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOCAL")]
	public partial class LOCAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLocal;
		
		private string _Direccion;
		
		private string _Ciudad;
		
		private string _Telefono;
		
		private string _Fax;
		
		private EntitySet<GUIA> _GUIA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLocalChanging(int value);
    partial void OnIdLocalChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnCiudadChanging(string value);
    partial void OnCiudadChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    #endregion
		
		public LOCAL()
		{
			this._GUIA = new EntitySet<GUIA>(new Action<GUIA>(this.attach_GUIA), new Action<GUIA>(this.detach_GUIA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLocal", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdLocal
		{
			get
			{
				return this._IdLocal;
			}
			set
			{
				if ((this._IdLocal != value))
				{
					this.OnIdLocalChanging(value);
					this.SendPropertyChanging();
					this._IdLocal = value;
					this.SendPropertyChanged("IdLocal");
					this.OnIdLocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(60)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(20)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this.OnCiudadChanging(value);
					this.SendPropertyChanging();
					this._Ciudad = value;
					this.SendPropertyChanged("Ciudad");
					this.OnCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(15)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOCAL_GUIA", Storage="_GUIA", ThisKey="IdLocal", OtherKey="IdLocal")]
		public EntitySet<GUIA> GUIA
		{
			get
			{
				return this._GUIA;
			}
			set
			{
				this._GUIA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GUIA(GUIA entity)
		{
			this.SendPropertyChanging();
			entity.LOCAL = this;
		}
		
		private void detach_GUIA(GUIA entity)
		{
			this.SendPropertyChanging();
			entity.LOCAL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDEN")]
	public partial class ORDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdOrden;
		
		private System.DateTime _FechaOrden;
		
		private System.Nullable<System.DateTime> _FechaEntrada;
		
		private EntitySet<ORDEN_DETALLE> _ORDEN_DETALLE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdOrdenChanging(int value);
    partial void OnIdOrdenChanged();
    partial void OnFechaOrdenChanging(System.DateTime value);
    partial void OnFechaOrdenChanged();
    partial void OnFechaEntradaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEntradaChanged();
    #endregion
		
		public ORDEN()
		{
			this._ORDEN_DETALLE = new EntitySet<ORDEN_DETALLE>(new Action<ORDEN_DETALLE>(this.attach_ORDEN_DETALLE), new Action<ORDEN_DETALLE>(this.detach_ORDEN_DETALLE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOrden", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdOrden
		{
			get
			{
				return this._IdOrden;
			}
			set
			{
				if ((this._IdOrden != value))
				{
					this.OnIdOrdenChanging(value);
					this.SendPropertyChanging();
					this._IdOrden = value;
					this.SendPropertyChanged("IdOrden");
					this.OnIdOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaOrden", DbType="DateTime NOT NULL")]
		public System.DateTime FechaOrden
		{
			get
			{
				return this._FechaOrden;
			}
			set
			{
				if ((this._FechaOrden != value))
				{
					this.OnFechaOrdenChanging(value);
					this.SendPropertyChanging();
					this._FechaOrden = value;
					this.SendPropertyChanged("FechaOrden");
					this.OnFechaOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntrada", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaEntrada
		{
			get
			{
				return this._FechaEntrada;
			}
			set
			{
				if ((this._FechaEntrada != value))
				{
					this.OnFechaEntradaChanging(value);
					this.SendPropertyChanging();
					this._FechaEntrada = value;
					this.SendPropertyChanged("FechaEntrada");
					this.OnFechaEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDEN_ORDEN_DETALLE", Storage="_ORDEN_DETALLE", ThisKey="IdOrden", OtherKey="IdOrden")]
		public EntitySet<ORDEN_DETALLE> ORDEN_DETALLE
		{
			get
			{
				return this._ORDEN_DETALLE;
			}
			set
			{
				this._ORDEN_DETALLE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ORDEN_DETALLE(ORDEN_DETALLE entity)
		{
			this.SendPropertyChanging();
			entity.ORDEN = this;
		}
		
		private void detach_ORDEN_DETALLE(ORDEN_DETALLE entity)
		{
			this.SendPropertyChanging();
			entity.ORDEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDEN_DETALLE")]
	public partial class ORDEN_DETALLE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdOrden;
		
		private int _IdProducto;
		
		private decimal _PrecioCompra;
		
		private short _CantidadSolicitada;
		
		private System.Nullable<short> _CantidadRecibida;
		
		private string _Estado;
		
		private EntityRef<ORDEN> _ORDEN;
		
		private EntityRef<PRODUCTO> _PRODUCTO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdOrdenChanging(int value);
    partial void OnIdOrdenChanged();
    partial void OnIdProductoChanging(int value);
    partial void OnIdProductoChanged();
    partial void OnPrecioCompraChanging(decimal value);
    partial void OnPrecioCompraChanged();
    partial void OnCantidadSolicitadaChanging(short value);
    partial void OnCantidadSolicitadaChanged();
    partial void OnCantidadRecibidaChanging(System.Nullable<short> value);
    partial void OnCantidadRecibidaChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
		
		public ORDEN_DETALLE()
		{
			this._ORDEN = default(EntityRef<ORDEN>);
			this._PRODUCTO = default(EntityRef<PRODUCTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOrden", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdOrden
		{
			get
			{
				return this._IdOrden;
			}
			set
			{
				if ((this._IdOrden != value))
				{
					if (this._ORDEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdOrdenChanging(value);
					this.SendPropertyChanging();
					this._IdOrden = value;
					this.SendPropertyChanged("IdOrden");
					this.OnIdOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					if (this._PRODUCTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProductoChanging(value);
					this.SendPropertyChanging();
					this._IdProducto = value;
					this.SendPropertyChanged("IdProducto");
					this.OnIdProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioCompra", DbType="Money NOT NULL")]
		public decimal PrecioCompra
		{
			get
			{
				return this._PrecioCompra;
			}
			set
			{
				if ((this._PrecioCompra != value))
				{
					this.OnPrecioCompraChanging(value);
					this.SendPropertyChanging();
					this._PrecioCompra = value;
					this.SendPropertyChanged("PrecioCompra");
					this.OnPrecioCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadSolicitada", DbType="SmallInt NOT NULL")]
		public short CantidadSolicitada
		{
			get
			{
				return this._CantidadSolicitada;
			}
			set
			{
				if ((this._CantidadSolicitada != value))
				{
					this.OnCantidadSolicitadaChanging(value);
					this.SendPropertyChanging();
					this._CantidadSolicitada = value;
					this.SendPropertyChanged("CantidadSolicitada");
					this.OnCantidadSolicitadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadRecibida", DbType="SmallInt")]
		public System.Nullable<short> CantidadRecibida
		{
			get
			{
				return this._CantidadRecibida;
			}
			set
			{
				if ((this._CantidadRecibida != value))
				{
					this.OnCantidadRecibidaChanging(value);
					this.SendPropertyChanging();
					this._CantidadRecibida = value;
					this.SendPropertyChanged("CantidadRecibida");
					this.OnCantidadRecibidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ORDEN_ORDEN_DETALLE", Storage="_ORDEN", ThisKey="IdOrden", OtherKey="IdOrden", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public ORDEN ORDEN
		{
			get
			{
				return this._ORDEN.Entity;
			}
			set
			{
				ORDEN previousValue = this._ORDEN.Entity;
				if (((previousValue != value) 
							|| (this._ORDEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ORDEN.Entity = null;
						previousValue.ORDEN_DETALLE.Remove(this);
					}
					this._ORDEN.Entity = value;
					if ((value != null))
					{
						value.ORDEN_DETALLE.Add(this);
						this._IdOrden = value.IdOrden;
					}
					else
					{
						this._IdOrden = default(int);
					}
					this.SendPropertyChanged("ORDEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_ORDEN_DETALLE", Storage="_PRODUCTO", ThisKey="IdProducto", OtherKey="IdProducto", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public PRODUCTO PRODUCTO
		{
			get
			{
				return this._PRODUCTO.Entity;
			}
			set
			{
				PRODUCTO previousValue = this._PRODUCTO.Entity;
				if (((previousValue != value) 
							|| (this._PRODUCTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PRODUCTO.Entity = null;
						previousValue.ORDEN_DETALLE.Remove(this);
					}
					this._PRODUCTO.Entity = value;
					if ((value != null))
					{
						value.ORDEN_DETALLE.Add(this);
						this._IdProducto = value.IdProducto;
					}
					else
					{
						this._IdProducto = default(int);
					}
					this.SendPropertyChanged("PRODUCTO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTO")]
	public partial class PRODUCTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdProducto;
		
		private int _IdCategoria;
		
		private string _Nombre;
		
		private string _UnidadMedida;
		
		private System.Nullable<decimal> _PrecioProveedor;
		
		private System.Nullable<short> _StockActual;
		
		private System.Nullable<short> _StockMinimo;
		
		private System.Nullable<decimal> _PrecioVenta;
		
		private EntitySet<GUIA_DETALLE> _GUIA_DETALLE;
		
		private EntitySet<ORDEN_DETALLE> _ORDEN_DETALLE;
		
		private EntityRef<CATEGORIA> _CATEGORIA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProductoChanging(int value);
    partial void OnIdProductoChanged();
    partial void OnIdCategoriaChanging(int value);
    partial void OnIdCategoriaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnUnidadMedidaChanging(string value);
    partial void OnUnidadMedidaChanged();
    partial void OnPrecioProveedorChanging(System.Nullable<decimal> value);
    partial void OnPrecioProveedorChanged();
    partial void OnStockActualChanging(System.Nullable<short> value);
    partial void OnStockActualChanged();
    partial void OnStockMinimoChanging(System.Nullable<short> value);
    partial void OnStockMinimoChanged();
    partial void OnPrecioVentaChanging(System.Nullable<decimal> value);
    partial void OnPrecioVentaChanged();
    #endregion
		
		public PRODUCTO()
		{
			this._GUIA_DETALLE = new EntitySet<GUIA_DETALLE>(new Action<GUIA_DETALLE>(this.attach_GUIA_DETALLE), new Action<GUIA_DETALLE>(this.detach_GUIA_DETALLE));
			this._ORDEN_DETALLE = new EntitySet<ORDEN_DETALLE>(new Action<ORDEN_DETALLE>(this.attach_ORDEN_DETALLE), new Action<ORDEN_DETALLE>(this.detach_ORDEN_DETALLE));
			this._CATEGORIA = default(EntityRef<CATEGORIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this.OnIdProductoChanging(value);
					this.SendPropertyChanging();
					this._IdProducto = value;
					this.SendPropertyChanged("IdProducto");
					this.OnIdProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					if (this._CATEGORIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IdCategoria = value;
					this.SendPropertyChanged("IdCategoria");
					this.OnIdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadMedida", DbType="VarChar(30)")]
		public string UnidadMedida
		{
			get
			{
				return this._UnidadMedida;
			}
			set
			{
				if ((this._UnidadMedida != value))
				{
					this.OnUnidadMedidaChanging(value);
					this.SendPropertyChanging();
					this._UnidadMedida = value;
					this.SendPropertyChanged("UnidadMedida");
					this.OnUnidadMedidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProveedor", DbType="Money")]
		public System.Nullable<decimal> PrecioProveedor
		{
			get
			{
				return this._PrecioProveedor;
			}
			set
			{
				if ((this._PrecioProveedor != value))
				{
					this.OnPrecioProveedorChanging(value);
					this.SendPropertyChanging();
					this._PrecioProveedor = value;
					this.SendPropertyChanged("PrecioProveedor");
					this.OnPrecioProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockActual", DbType="SmallInt")]
		public System.Nullable<short> StockActual
		{
			get
			{
				return this._StockActual;
			}
			set
			{
				if ((this._StockActual != value))
				{
					this.OnStockActualChanging(value);
					this.SendPropertyChanging();
					this._StockActual = value;
					this.SendPropertyChanged("StockActual");
					this.OnStockActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMinimo", DbType="SmallInt")]
		public System.Nullable<short> StockMinimo
		{
			get
			{
				return this._StockMinimo;
			}
			set
			{
				if ((this._StockMinimo != value))
				{
					this.OnStockMinimoChanging(value);
					this.SendPropertyChanging();
					this._StockMinimo = value;
					this.SendPropertyChanged("StockMinimo");
					this.OnStockMinimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVenta", DbType="Money")]
		public System.Nullable<decimal> PrecioVenta
		{
			get
			{
				return this._PrecioVenta;
			}
			set
			{
				if ((this._PrecioVenta != value))
				{
					this.OnPrecioVentaChanging(value);
					this.SendPropertyChanging();
					this._PrecioVenta = value;
					this.SendPropertyChanged("PrecioVenta");
					this.OnPrecioVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_GUIA_DETALLE", Storage="_GUIA_DETALLE", ThisKey="IdProducto", OtherKey="IdProducto")]
		public EntitySet<GUIA_DETALLE> GUIA_DETALLE
		{
			get
			{
				return this._GUIA_DETALLE;
			}
			set
			{
				this._GUIA_DETALLE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCTO_ORDEN_DETALLE", Storage="_ORDEN_DETALLE", ThisKey="IdProducto", OtherKey="IdProducto")]
		public EntitySet<ORDEN_DETALLE> ORDEN_DETALLE
		{
			get
			{
				return this._ORDEN_DETALLE;
			}
			set
			{
				this._ORDEN_DETALLE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIA_PRODUCTO", Storage="_CATEGORIA", ThisKey="IdCategoria", OtherKey="IdCategoria", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CATEGORIA CATEGORIA
		{
			get
			{
				return this._CATEGORIA.Entity;
			}
			set
			{
				CATEGORIA previousValue = this._CATEGORIA.Entity;
				if (((previousValue != value) 
							|| (this._CATEGORIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CATEGORIA.Entity = null;
						previousValue.PRODUCTO.Remove(this);
					}
					this._CATEGORIA.Entity = value;
					if ((value != null))
					{
						value.PRODUCTO.Add(this);
						this._IdCategoria = value.IdCategoria;
					}
					else
					{
						this._IdCategoria = default(int);
					}
					this.SendPropertyChanged("CATEGORIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GUIA_DETALLE(GUIA_DETALLE entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = this;
		}
		
		private void detach_GUIA_DETALLE(GUIA_DETALLE entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = null;
		}
		
		private void attach_ORDEN_DETALLE(ORDEN_DETALLE entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = this;
		}
		
		private void detach_ORDEN_DETALLE(ORDEN_DETALLE entity)
		{
			this.SendPropertyChanging();
			entity.PRODUCTO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTO_PROVEEDOR")]
	public partial class PRODUCTO_PROVEEDOR
	{
		
		private System.Nullable<int> _IdProducto;
		
		private System.Nullable<int> _IdProveedor;
		
		private System.Nullable<System.DateTime> _FechaEntrega;
		
		public PRODUCTO_PROVEEDOR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int")]
		public System.Nullable<int> IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Int")]
		public System.Nullable<int> IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntrega", DbType="Date")]
		public System.Nullable<System.DateTime> FechaEntrega
		{
			get
			{
				return this._FechaEntrega;
			}
			set
			{
				if ((this._FechaEntrega != value))
				{
					this._FechaEntrega = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROVEEDOR")]
	public partial class PROVEEDOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdProveedor;
		
		private string _CedProveedor;
		
		private string _Nombre;
		
		private string _Representante;
		
		private string _Direccion;
		
		private string _Ciudad;
		
		private string _Telefono;
		
		private string _Fax;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProveedorChanging(int value);
    partial void OnIdProveedorChanged();
    partial void OnCedProveedorChanging(string value);
    partial void OnCedProveedorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnRepresentanteChanging(string value);
    partial void OnRepresentanteChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnCiudadChanging(string value);
    partial void OnCiudadChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    #endregion
		
		public PROVEEDOR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this.OnIdProveedorChanging(value);
					this.SendPropertyChanging();
					this._IdProveedor = value;
					this.SendPropertyChanged("IdProveedor");
					this.OnIdProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CedProveedor", DbType="VarChar(10)")]
		public string CedProveedor
		{
			get
			{
				return this._CedProveedor;
			}
			set
			{
				if ((this._CedProveedor != value))
				{
					this.OnCedProveedorChanging(value);
					this.SendPropertyChanging();
					this._CedProveedor = value;
					this.SendPropertyChanged("CedProveedor");
					this.OnCedProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Representante", DbType="VarChar(30)")]
		public string Representante
		{
			get
			{
				return this._Representante;
			}
			set
			{
				if ((this._Representante != value))
				{
					this.OnRepresentanteChanging(value);
					this.SendPropertyChanging();
					this._Representante = value;
					this.SendPropertyChanged("Representante");
					this.OnRepresentanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(60)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(15)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this.OnCiudadChanging(value);
					this.SendPropertyChanging();
					this._Ciudad = value;
					this.SendPropertyChanged("Ciudad");
					this.OnCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(15)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANSPORTISTA")]
	public partial class TRANSPORTISTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdTransportista;
		
		private string _CedTransportista;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Ciudad;
		
		private string _Telefono;
		
		private EntitySet<GUIA> _GUIA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTransportistaChanging(string value);
    partial void OnIdTransportistaChanged();
    partial void OnCedTransportistaChanging(string value);
    partial void OnCedTransportistaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnCiudadChanging(string value);
    partial void OnCiudadChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    #endregion
		
		public TRANSPORTISTA()
		{
			this._GUIA = new EntitySet<GUIA>(new Action<GUIA>(this.attach_GUIA), new Action<GUIA>(this.detach_GUIA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTransportista", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdTransportista
		{
			get
			{
				return this._IdTransportista;
			}
			set
			{
				if ((this._IdTransportista != value))
				{
					this.OnIdTransportistaChanging(value);
					this.SendPropertyChanging();
					this._IdTransportista = value;
					this.SendPropertyChanged("IdTransportista");
					this.OnIdTransportistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CedTransportista", DbType="VarChar(10)")]
		public string CedTransportista
		{
			get
			{
				return this._CedTransportista;
			}
			set
			{
				if ((this._CedTransportista != value))
				{
					this.OnCedTransportistaChanging(value);
					this.SendPropertyChanging();
					this._CedTransportista = value;
					this.SendPropertyChanged("CedTransportista");
					this.OnCedTransportistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(60)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(15)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this.OnCiudadChanging(value);
					this.SendPropertyChanging();
					this._Ciudad = value;
					this.SendPropertyChanged("Ciudad");
					this.OnCiudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANSPORTISTA_GUIA", Storage="_GUIA", ThisKey="IdTransportista", OtherKey="Transportista")]
		public EntitySet<GUIA> GUIA
		{
			get
			{
				return this._GUIA;
			}
			set
			{
				this._GUIA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GUIA(GUIA entity)
		{
			this.SendPropertyChanging();
			entity.TRANSPORTISTA1 = this;
		}
		
		private void detach_GUIA(GUIA entity)
		{
			this.SendPropertyChanging();
			entity.TRANSPORTISTA1 = null;
		}
	}
	
	public partial class SP_VerCategoriaResult
	{
		
		private int _IdCategoria;
		
		private string _Categoria;
		
		private string _Descripcion;
		
		public SP_VerCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(40)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarCategoria_FiltroResult
	{
		
		private int _IdCategoria;
		
		private string _Categoria;
		
		private string _Descripcion;
		
		public SP_ListarCategoria_FiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(40)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarLocal_FiltroResult
	{
		
		private int _IdLocal;
		
		private string _Direccion;
		
		private string _Ciudad;
		
		private string _Telefono;
		
		private string _Fax;
		
		public SP_ListarLocal_FiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLocal", DbType="Int NOT NULL")]
		public int IdLocal
		{
			get
			{
				return this._IdLocal;
			}
			set
			{
				if ((this._IdLocal != value))
				{
					this._IdLocal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(60)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(20)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this._Ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(15)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
	}
	
	public partial class SP_ListarProducto_FiltroResult
	{
		
		private int _IdProducto;
		
		private int _IdCategoria;
		
		private string _Nombre;
		
		private string _UnidadMedida;
		
		private decimal _PrecioProveedor;
		
		private short _StockActual;
		
		private short _StockMinimo;
		
		private decimal _PrecioVenta;
		
		public SP_ListarProducto_FiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadMedida", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UnidadMedida
		{
			get
			{
				return this._UnidadMedida;
			}
			set
			{
				if ((this._UnidadMedida != value))
				{
					this._UnidadMedida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProveedor", DbType="Money NOT NULL")]
		public decimal PrecioProveedor
		{
			get
			{
				return this._PrecioProveedor;
			}
			set
			{
				if ((this._PrecioProveedor != value))
				{
					this._PrecioProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockActual", DbType="SmallInt NOT NULL")]
		public short StockActual
		{
			get
			{
				return this._StockActual;
			}
			set
			{
				if ((this._StockActual != value))
				{
					this._StockActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMinimo", DbType="SmallInt NOT NULL")]
		public short StockMinimo
		{
			get
			{
				return this._StockMinimo;
			}
			set
			{
				if ((this._StockMinimo != value))
				{
					this._StockMinimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVenta", DbType="Money NOT NULL")]
		public decimal PrecioVenta
		{
			get
			{
				return this._PrecioVenta;
			}
			set
			{
				if ((this._PrecioVenta != value))
				{
					this._PrecioVenta = value;
				}
			}
		}
	}
	
	public partial class SP_ListarProveedor_FiltroResult
	{
		
		private int _IdProveedor;
		
		private string _CedProveedor;
		
		private string _Nombre;
		
		private string _Representante;
		
		private string _Direccion;
		
		private string _Ciudad;
		
		private string _Telefono;
		
		private string _Fax;
		
		public SP_ListarProveedor_FiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Int NOT NULL")]
		public int IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CedProveedor", DbType="VarChar(10)")]
		public string CedProveedor
		{
			get
			{
				return this._CedProveedor;
			}
			set
			{
				if ((this._CedProveedor != value))
				{
					this._CedProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Representante", DbType="VarChar(30)")]
		public string Representante
		{
			get
			{
				return this._Representante;
			}
			set
			{
				if ((this._Representante != value))
				{
					this._Representante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(60)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(15)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this._Ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(15)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
	}
	
	public partial class SP_ListarGuia_FiltroResult
	{
		
		private int _IdGuia;
		
		private int _IdLocal;
		
		private System.DateTime _FechaSalida;
		
		private string _Transportista;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<int> _cantidad_Item;
		
		public SP_ListarGuia_FiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdGuia", DbType="Int NOT NULL")]
		public int IdGuia
		{
			get
			{
				return this._IdGuia;
			}
			set
			{
				if ((this._IdGuia != value))
				{
					this._IdGuia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLocal", DbType="Int NOT NULL")]
		public int IdLocal
		{
			get
			{
				return this._IdLocal;
			}
			set
			{
				if ((this._IdLocal != value))
				{
					this._IdLocal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSalida", DbType="DateTime NOT NULL")]
		public System.DateTime FechaSalida
		{
			get
			{
				return this._FechaSalida;
			}
			set
			{
				if ((this._FechaSalida != value))
				{
					this._FechaSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transportista", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Transportista
		{
			get
			{
				return this._Transportista;
			}
			set
			{
				if ((this._Transportista != value))
				{
					this._Transportista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_Item", DbType="Int")]
		public System.Nullable<int> cantidad_Item
		{
			get
			{
				return this._cantidad_Item;
			}
			set
			{
				if ((this._cantidad_Item != value))
				{
					this._cantidad_Item = value;
				}
			}
		}
	}
	
	public partial class SP_ListarOrden_FiltroResult
	{
		
		private int _IdOrden;
		
		private System.DateTime _FechaOrden;
		
		private System.Nullable<System.DateTime> _FechaEntrada;
		
		public SP_ListarOrden_FiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOrden", DbType="Int NOT NULL")]
		public int IdOrden
		{
			get
			{
				return this._IdOrden;
			}
			set
			{
				if ((this._IdOrden != value))
				{
					this._IdOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaOrden", DbType="DateTime NOT NULL")]
		public System.DateTime FechaOrden
		{
			get
			{
				return this._FechaOrden;
			}
			set
			{
				if ((this._FechaOrden != value))
				{
					this._FechaOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntrada", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaEntrada
		{
			get
			{
				return this._FechaEntrada;
			}
			set
			{
				if ((this._FechaEntrada != value))
				{
					this._FechaEntrada = value;
				}
			}
		}
	}
	
	public partial class SP_ListarTransportista_FiltroResult
	{
		
		private string _IdTransportista;
		
		private string _CedTransportista;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Ciudad;
		
		private string _Telefono;
		
		public SP_ListarTransportista_FiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTransportista", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string IdTransportista
		{
			get
			{
				return this._IdTransportista;
			}
			set
			{
				if ((this._IdTransportista != value))
				{
					this._IdTransportista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CedTransportista", DbType="VarChar(10)")]
		public string CedTransportista
		{
			get
			{
				return this._CedTransportista;
			}
			set
			{
				if ((this._CedTransportista != value))
				{
					this._CedTransportista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(60)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciudad", DbType="VarChar(15)")]
		public string Ciudad
		{
			get
			{
				return this._Ciudad;
			}
			set
			{
				if ((this._Ciudad != value))
				{
					this._Ciudad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(15)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
	}
	
	public partial class SP_ListarProductoCategoriaFiltroResult
	{
		
		private string _Categoria;
		
		private string _Nombre;
		
		private string _Proveedor;
		
		private string _UnidadMedida;
		
		private int _IdProducto;
		
		private decimal _PrecioProveedor;
		
		private short _StockActual;
		
		private short _StockMinimo;
		
		private decimal _PrecioVenta;
		
		public SP_ListarProductoCategoriaFiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proveedor", DbType="VarChar(40)")]
		public string Proveedor
		{
			get
			{
				return this._Proveedor;
			}
			set
			{
				if ((this._Proveedor != value))
				{
					this._Proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadMedida", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UnidadMedida
		{
			get
			{
				return this._UnidadMedida;
			}
			set
			{
				if ((this._UnidadMedida != value))
				{
					this._UnidadMedida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProveedor", DbType="Money NOT NULL")]
		public decimal PrecioProveedor
		{
			get
			{
				return this._PrecioProveedor;
			}
			set
			{
				if ((this._PrecioProveedor != value))
				{
					this._PrecioProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockActual", DbType="SmallInt NOT NULL")]
		public short StockActual
		{
			get
			{
				return this._StockActual;
			}
			set
			{
				if ((this._StockActual != value))
				{
					this._StockActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMinimo", DbType="SmallInt NOT NULL")]
		public short StockMinimo
		{
			get
			{
				return this._StockMinimo;
			}
			set
			{
				if ((this._StockMinimo != value))
				{
					this._StockMinimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVenta", DbType="Money NOT NULL")]
		public decimal PrecioVenta
		{
			get
			{
				return this._PrecioVenta;
			}
			set
			{
				if ((this._PrecioVenta != value))
				{
					this._PrecioVenta = value;
				}
			}
		}
	}
	
	public partial class SP_InsertarProductoResult
	{
		
		private int _IdProducto;
		
		public SP_InsertarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
	}
	
	public partial class SP_GetProductoResult
	{
		
		private int _IdProducto;
		
		private int _IdCategoria;
		
		private string _Nombre;
		
		private string _UnidadMedida;
		
		private decimal _PrecioProveedor;
		
		private short _StockActual;
		
		private short _StockMinimo;
		
		private decimal _PrecioVenta;
		
		public SP_GetProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadMedida", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string UnidadMedida
		{
			get
			{
				return this._UnidadMedida;
			}
			set
			{
				if ((this._UnidadMedida != value))
				{
					this._UnidadMedida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProveedor", DbType="Money NOT NULL")]
		public decimal PrecioProveedor
		{
			get
			{
				return this._PrecioProveedor;
			}
			set
			{
				if ((this._PrecioProveedor != value))
				{
					this._PrecioProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockActual", DbType="SmallInt NOT NULL")]
		public short StockActual
		{
			get
			{
				return this._StockActual;
			}
			set
			{
				if ((this._StockActual != value))
				{
					this._StockActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMinimo", DbType="SmallInt NOT NULL")]
		public short StockMinimo
		{
			get
			{
				return this._StockMinimo;
			}
			set
			{
				if ((this._StockMinimo != value))
				{
					this._StockMinimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVenta", DbType="Money NOT NULL")]
		public decimal PrecioVenta
		{
			get
			{
				return this._PrecioVenta;
			}
			set
			{
				if ((this._PrecioVenta != value))
				{
					this._PrecioVenta = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
