#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="camionesdb")]
	public partial class CamionesdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCAMION(CAMION instance);
    partial void UpdateCAMION(CAMION instance);
    partial void DeleteCAMION(CAMION instance);
    partial void InsertCLIENTE(CLIENTE instance);
    partial void UpdateCLIENTE(CLIENTE instance);
    partial void DeleteCLIENTE(CLIENTE instance);
    partial void InsertGUIA(GUIA instance);
    partial void UpdateGUIA(GUIA instance);
    partial void DeleteGUIA(GUIA instance);
    partial void InsertENCOMIENDAS(ENCOMIENDAS instance);
    partial void UpdateENCOMIENDAS(ENCOMIENDAS instance);
    partial void DeleteENCOMIENDAS(ENCOMIENDAS instance);
    #endregion
		
		public CamionesdbDataContext() : 
				base(global::Datos.Properties.Settings.Default.camionesdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CamionesdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CamionesdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CamionesdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CamionesdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CAMION> CAMION
		{
			get
			{
				return this.GetTable<CAMION>();
			}
		}
		
		public System.Data.Linq.Table<GUIA_DETALLE> GUIA_DETALLE
		{
			get
			{
				return this.GetTable<GUIA_DETALLE>();
			}
		}
		
		public System.Data.Linq.Table<CLIENTE> CLIENTE
		{
			get
			{
				return this.GetTable<CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<GUIA> GUIA
		{
			get
			{
				return this.GetTable<GUIA>();
			}
		}
		
		public System.Data.Linq.Table<ENCOMIENDAS> ENCOMIENDAS
		{
			get
			{
				return this.GetTable<ENCOMIENDAS>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarCamion")]
		public int SP_InsertarCamion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> peso_max, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numero_viajes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, peso_max, estado, numero_viajes);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarGuia")]
		public ISingleResult<SP_ListarGuiaResult> SP_ListarGuia()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarGuiaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarCliente")]
		public int SP_InsertarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string direccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula, nombres, telefono, direccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarGuia")]
		public int SP_InsertarGuia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_camion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha_envio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad_encomiendas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> peso_total)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_camion, fecha_envio, cantidad_encomiendas, peso_total);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarGuiaDetalle")]
		public int SP_InsertarGuiaDetalle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_encomienda, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_guia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_encomienda, id_guia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarCamiones")]
		public ISingleResult<SP_ListarCamionesResult> SP_ListarCamiones()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarCamionesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarClientes")]
		public ISingleResult<SP_ListarClientesResult> SP_ListarClientes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarClientesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarEncomiendas")]
		public ISingleResult<SP_ListarEncomiendasResult> SP_ListarEncomiendas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarEncomiendasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarEncomienda")]
		public int SP_InsertarEncomienda([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> peso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> costo_envio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_cliente, codigo, peso, direccion, costo_envio, estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerGuiaObjeto")]
		public ISingleResult<SP_ObtenerGuiaObjetoResult> SP_ObtenerGuiaObjeto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_camion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha_envio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad_encomiendas, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> peso_total)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_camion, fecha_envio, cantidad_encomiendas, peso_total);
			return ((ISingleResult<SP_ObtenerGuiaObjetoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarEncomiendaEstado")]
		public int SP_ActualizarEncomiendaEstado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarCamionDisponible")]
		public int SP_ActualizarCamionDisponible([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarCamionOcupado")]
		public int SP_ActualizarCamionOcupado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarEncomiendasPorEntregar")]
		public ISingleResult<SP_ListarEncomiendasPorEntregarResult> SP_ListarEncomiendasPorEntregar()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_ListarEncomiendasPorEntregarResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAMION")]
	public partial class CAMION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<decimal> _peso_max;
		
		private string _estado;
		
		private System.Nullable<int> _numero_viajes;
		
		private EntitySet<GUIA> _GUIA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onpeso_maxChanging(System.Nullable<decimal> value);
    partial void Onpeso_maxChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void Onnumero_viajesChanging(System.Nullable<int> value);
    partial void Onnumero_viajesChanged();
    #endregion
		
		public CAMION()
		{
			this._GUIA = new EntitySet<GUIA>(new Action<GUIA>(this.attach_GUIA), new Action<GUIA>(this.detach_GUIA));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso_max", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> peso_max
		{
			get
			{
				return this._peso_max;
			}
			set
			{
				if ((this._peso_max != value))
				{
					this.Onpeso_maxChanging(value);
					this.SendPropertyChanging();
					this._peso_max = value;
					this.SendPropertyChanged("peso_max");
					this.Onpeso_maxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_viajes", DbType="Int")]
		public System.Nullable<int> numero_viajes
		{
			get
			{
				return this._numero_viajes;
			}
			set
			{
				if ((this._numero_viajes != value))
				{
					this.Onnumero_viajesChanging(value);
					this.SendPropertyChanging();
					this._numero_viajes = value;
					this.SendPropertyChanged("numero_viajes");
					this.Onnumero_viajesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAMION_GUIA", Storage="_GUIA", ThisKey="id", OtherKey="id_camion")]
		public EntitySet<GUIA> GUIA
		{
			get
			{
				return this._GUIA;
			}
			set
			{
				this._GUIA.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GUIA(GUIA entity)
		{
			this.SendPropertyChanging();
			entity.CAMION = this;
		}
		
		private void detach_GUIA(GUIA entity)
		{
			this.SendPropertyChanging();
			entity.CAMION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GUIA_DETALLE")]
	public partial class GUIA_DETALLE
	{
		
		private int _id_encomienda;
		
		private int _id_guia;
		
		public GUIA_DETALLE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_encomienda", DbType="Int NOT NULL")]
		public int id_encomienda
		{
			get
			{
				return this._id_encomienda;
			}
			set
			{
				if ((this._id_encomienda != value))
				{
					this._id_encomienda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_guia", DbType="Int NOT NULL")]
		public int id_guia
		{
			get
			{
				return this._id_guia;
			}
			set
			{
				if ((this._id_guia != value))
				{
					this._id_guia = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTE")]
	public partial class CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cedula;
		
		private string _nombres;
		
		private string _telefono;
		
		private string _direccion;
		
		private EntitySet<ENCOMIENDAS> _ENCOMIENDAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncedulaChanging(string value);
    partial void OncedulaChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    #endregion
		
		public CLIENTE()
		{
			this._ENCOMIENDAS = new EntitySet<ENCOMIENDAS>(new Action<ENCOMIENDAS>(this.attach_ENCOMIENDAS), new Action<ENCOMIENDAS>(this.detach_ENCOMIENDAS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="NVarChar(50)")]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="NVarChar(50)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(50)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_ENCOMIENDAS", Storage="_ENCOMIENDAS", ThisKey="id", OtherKey="id_cliente")]
		public EntitySet<ENCOMIENDAS> ENCOMIENDAS
		{
			get
			{
				return this._ENCOMIENDAS;
			}
			set
			{
				this._ENCOMIENDAS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ENCOMIENDAS(ENCOMIENDAS entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = this;
		}
		
		private void detach_ENCOMIENDAS(ENCOMIENDAS entity)
		{
			this.SendPropertyChanging();
			entity.CLIENTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GUIA")]
	public partial class GUIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_camion;
		
		private System.Nullable<System.DateTime> _fecha_envio;
		
		private System.Nullable<int> _cantidad_encomiendas;
		
		private System.Nullable<decimal> _peso_total;
		
		private EntityRef<CAMION> _CAMION;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_camionChanging(System.Nullable<int> value);
    partial void Onid_camionChanged();
    partial void Onfecha_envioChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_envioChanged();
    partial void Oncantidad_encomiendasChanging(System.Nullable<int> value);
    partial void Oncantidad_encomiendasChanged();
    partial void Onpeso_totalChanging(System.Nullable<decimal> value);
    partial void Onpeso_totalChanged();
    #endregion
		
		public GUIA()
		{
			this._CAMION = default(EntityRef<CAMION>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_camion", DbType="Int")]
		public System.Nullable<int> id_camion
		{
			get
			{
				return this._id_camion;
			}
			set
			{
				if ((this._id_camion != value))
				{
					if (this._CAMION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_camionChanging(value);
					this.SendPropertyChanging();
					this._id_camion = value;
					this.SendPropertyChanged("id_camion");
					this.Onid_camionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_envio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_envio
		{
			get
			{
				return this._fecha_envio;
			}
			set
			{
				if ((this._fecha_envio != value))
				{
					this.Onfecha_envioChanging(value);
					this.SendPropertyChanging();
					this._fecha_envio = value;
					this.SendPropertyChanged("fecha_envio");
					this.Onfecha_envioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_encomiendas", DbType="Int")]
		public System.Nullable<int> cantidad_encomiendas
		{
			get
			{
				return this._cantidad_encomiendas;
			}
			set
			{
				if ((this._cantidad_encomiendas != value))
				{
					this.Oncantidad_encomiendasChanging(value);
					this.SendPropertyChanging();
					this._cantidad_encomiendas = value;
					this.SendPropertyChanged("cantidad_encomiendas");
					this.Oncantidad_encomiendasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso_total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> peso_total
		{
			get
			{
				return this._peso_total;
			}
			set
			{
				if ((this._peso_total != value))
				{
					this.Onpeso_totalChanging(value);
					this.SendPropertyChanging();
					this._peso_total = value;
					this.SendPropertyChanged("peso_total");
					this.Onpeso_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAMION_GUIA", Storage="_CAMION", ThisKey="id_camion", OtherKey="id", IsForeignKey=true)]
		public CAMION CAMION
		{
			get
			{
				return this._CAMION.Entity;
			}
			set
			{
				CAMION previousValue = this._CAMION.Entity;
				if (((previousValue != value) 
							|| (this._CAMION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAMION.Entity = null;
						previousValue.GUIA.Remove(this);
					}
					this._CAMION.Entity = value;
					if ((value != null))
					{
						value.GUIA.Add(this);
						this._id_camion = value.id;
					}
					else
					{
						this._id_camion = default(Nullable<int>);
					}
					this.SendPropertyChanged("CAMION");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ENCOMIENDAS")]
	public partial class ENCOMIENDAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_cliente;
		
		private string _codigo;
		
		private System.Nullable<decimal> _peso;
		
		private string _direccion;
		
		private System.Nullable<decimal> _costo_envio;
		
		private string _estado;
		
		private EntityRef<CLIENTE> _CLIENTE;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_clienteChanging(System.Nullable<int> value);
    partial void Onid_clienteChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnpesoChanging(System.Nullable<decimal> value);
    partial void OnpesoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Oncosto_envioChanging(System.Nullable<decimal> value);
    partial void Oncosto_envioChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public ENCOMIENDAS()
		{
			this._CLIENTE = default(EntityRef<CLIENTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int")]
		public System.Nullable<int> id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._CLIENTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NVarChar(50)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this.OnpesoChanging(value);
					this.SendPropertyChanging();
					this._peso = value;
					this.SendPropertyChanged("peso");
					this.OnpesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo_envio", DbType="Money")]
		public System.Nullable<decimal> costo_envio
		{
			get
			{
				return this._costo_envio;
			}
			set
			{
				if ((this._costo_envio != value))
				{
					this.Oncosto_envioChanging(value);
					this.SendPropertyChanging();
					this._costo_envio = value;
					this.SendPropertyChanged("costo_envio");
					this.Oncosto_envioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CLIENTE_ENCOMIENDAS", Storage="_CLIENTE", ThisKey="id_cliente", OtherKey="id", IsForeignKey=true)]
		public CLIENTE CLIENTE
		{
			get
			{
				return this._CLIENTE.Entity;
			}
			set
			{
				CLIENTE previousValue = this._CLIENTE.Entity;
				if (((previousValue != value) 
							|| (this._CLIENTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CLIENTE.Entity = null;
						previousValue.ENCOMIENDAS.Remove(this);
					}
					this._CLIENTE.Entity = value;
					if ((value != null))
					{
						value.ENCOMIENDAS.Add(this);
						this._id_cliente = value.id;
					}
					else
					{
						this._id_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("CLIENTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_ListarGuiaResult
	{
		
		private int _id;
		
		private System.Nullable<int> _id_camion;
		
		private System.Nullable<System.DateTime> _fecha_envio;
		
		private System.Nullable<int> _cantidad_encomiendas;
		
		private System.Nullable<decimal> _peso_total;
		
		public SP_ListarGuiaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_camion", DbType="Int")]
		public System.Nullable<int> id_camion
		{
			get
			{
				return this._id_camion;
			}
			set
			{
				if ((this._id_camion != value))
				{
					this._id_camion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_envio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_envio
		{
			get
			{
				return this._fecha_envio;
			}
			set
			{
				if ((this._fecha_envio != value))
				{
					this._fecha_envio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_encomiendas", DbType="Int")]
		public System.Nullable<int> cantidad_encomiendas
		{
			get
			{
				return this._cantidad_encomiendas;
			}
			set
			{
				if ((this._cantidad_encomiendas != value))
				{
					this._cantidad_encomiendas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso_total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> peso_total
		{
			get
			{
				return this._peso_total;
			}
			set
			{
				if ((this._peso_total != value))
				{
					this._peso_total = value;
				}
			}
		}
	}
	
	public partial class SP_ListarCamionesResult
	{
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<decimal> _peso_max;
		
		private string _estado;
		
		private System.Nullable<int> _numero_viajes;
		
		public SP_ListarCamionesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso_max", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> peso_max
		{
			get
			{
				return this._peso_max;
			}
			set
			{
				if ((this._peso_max != value))
				{
					this._peso_max = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_viajes", DbType="Int")]
		public System.Nullable<int> numero_viajes
		{
			get
			{
				return this._numero_viajes;
			}
			set
			{
				if ((this._numero_viajes != value))
				{
					this._numero_viajes = value;
				}
			}
		}
	}
	
	public partial class SP_ListarClientesResult
	{
		
		private int _id;
		
		private string _cedula;
		
		private string _nombres;
		
		private string _telefono;
		
		private string _direccion;
		
		public SP_ListarClientesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="NVarChar(50)")]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="NVarChar(50)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this._nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(50)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarEncomiendasResult
	{
		
		private int _id;
		
		private System.Nullable<int> _id_cliente;
		
		private string _codigo;
		
		private System.Nullable<decimal> _peso;
		
		private string _direccion;
		
		private System.Nullable<decimal> _costo_envio;
		
		private string _estado;
		
		public SP_ListarEncomiendasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int")]
		public System.Nullable<int> id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this._id_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NVarChar(50)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo_envio", DbType="Money")]
		public System.Nullable<decimal> costo_envio
		{
			get
			{
				return this._costo_envio;
			}
			set
			{
				if ((this._costo_envio != value))
				{
					this._costo_envio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
	}
	
	public partial class SP_ObtenerGuiaObjetoResult
	{
		
		private int _id;
		
		private System.Nullable<int> _id_camion;
		
		private System.Nullable<System.DateTime> _fecha_envio;
		
		private System.Nullable<int> _cantidad_encomiendas;
		
		private System.Nullable<decimal> _peso_total;
		
		public SP_ObtenerGuiaObjetoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_camion", DbType="Int")]
		public System.Nullable<int> id_camion
		{
			get
			{
				return this._id_camion;
			}
			set
			{
				if ((this._id_camion != value))
				{
					this._id_camion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_envio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_envio
		{
			get
			{
				return this._fecha_envio;
			}
			set
			{
				if ((this._fecha_envio != value))
				{
					this._fecha_envio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_encomiendas", DbType="Int")]
		public System.Nullable<int> cantidad_encomiendas
		{
			get
			{
				return this._cantidad_encomiendas;
			}
			set
			{
				if ((this._cantidad_encomiendas != value))
				{
					this._cantidad_encomiendas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso_total", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> peso_total
		{
			get
			{
				return this._peso_total;
			}
			set
			{
				if ((this._peso_total != value))
				{
					this._peso_total = value;
				}
			}
		}
	}
	
	public partial class SP_ListarEncomiendasPorEntregarResult
	{
		
		private int _id;
		
		private System.Nullable<int> _id_cliente;
		
		private string _codigo;
		
		private System.Nullable<decimal> _peso;
		
		private string _direccion;
		
		private System.Nullable<decimal> _costo_envio;
		
		private string _estado;
		
		public SP_ListarEncomiendasPorEntregarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int")]
		public System.Nullable<int> id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this._id_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NVarChar(50)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this._codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo_envio", DbType="Money")]
		public System.Nullable<decimal> costo_envio
		{
			get
			{
				return this._costo_envio;
			}
			set
			{
				if ((this._costo_envio != value))
				{
					this._costo_envio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="NVarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
